version: "3.9"

services:
  fastapi-app:
    build: .
    ports:
      - "8000:8000"
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"  
    privileged: true  
    environment:
      - SERIAL_PORT=/dev/ttyUSB0

